### ISSUE TITLE
非常有趣的项目

### ISSUE THREAD

**Issue by elliottzheng** [ravenxrz/CopyActionDaemojn#1]
拖拽复制是一个实用且常用的功能，但其稳定性一直困扰着我，这个问题是由于所使用的nodejs第三方库不稳定造成的。你的仓库提供了一个新的解决思路，以外部程序提供拖拽复制功能。不过有一些点需要指出
1. 遇到bug应首先向CopyTranslator仓库反馈，提供详细的出错报告，以便我更好地定位问题和改进软件。
2. 软件需要依赖JRE比较大程度限制了其应用，如果能够使用c++或者其他不依赖虚拟机或运行时地语言实现能够极大地拓展其应用。

**Comment by ravenxrz** [comment]
没想到作者大大看到了这个项目。
因为看了下CopyTranslator的issues，感觉您是知道这个bug的，所以就没再提issue。java依赖jre倒确实是个比较严重的问题。
不过毕竟这是个用来过渡的小项目，所以更期待大佬早日解决这个bug，然后我也不用开两个进程了。哈哈哈。
